# Generated by Django 2.2.3 on 2019-10-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='EDUCATION',
            new_name='education',
        ),
    ]
